import { Button, Card, Form, Input, Modal, Select, Space, Switch, Table, Tag, Typography, message } from 'antd'
import { BellOutlined, DeleteOutlined, EditOutlined, PlusOutlined, QuestionCircleOutlined } from '@ant-design/icons'
import { useState } from 'react'

const { Title, Text } = Typography
type Rule = { id: string; name: string; type: string; target: string; threshold: string; duration: string; enabled: boolean; updated: string }
const initialRules: Rule[] = [
  { id: 'rule-1', name: '办公楼大厅超员', type: '超员告警', target: '研发楼 A 座 · 一层大厅', threshold: '≥ 120 人', duration: '持续 3 分钟', enabled: true, updated: '2026-07-17 16:20' },
  { id: 'rule-2', name: '餐厅高峰超员', type: '超员告警', target: '食堂一层 · 入口大厅', threshold: '≥ 80 人', duration: '持续 5 分钟', enabled: true, updated: '2026-07-16 11:08' },
  { id: 'rule-3', name: '出入口聚集检测', type: '聚集告警', target: '园区南门 · 人行通道', threshold: '≥ 20 人', duration: '持续 5 分钟', enabled: true, updated: '2026-07-15 09:42' },
  { id: 'rule-4', name: '异常行为识别', type: '异常行为', target: '全园区', threshold: '算法触发', duration: '实时', enabled: false, updated: '待行为算法上线' },
]

export default function AlertRulesPage() {
  const [rules, setRules] = useState(initialRules)
  const [modalOpen, setModalOpen] = useState(false)
  const [messageApi, contextHolder] = message.useMessage()
  return <div className="page-stack">{contextHolder}<div className="page-heading"><div><Title level={3}>告警规则</Title><Text type="secondary">配置超员、聚集告警规则，异常行为告警待算法能力上线后开放</Text></div><Button type="primary" icon={<PlusOutlined />} onClick={() => setModalOpen(true)}>新增规则</Button></div><Card className="panel-card"><Table rowKey="id" dataSource={rules} pagination={false} columns={[{ title: '规则名称', dataIndex: 'name', render: (value: string, record: Rule) => <div className="rule-name"><BellOutlined /><span><strong>{value}</strong>{record.type === '异常行为' && <Tag color="default">未来迭代</Tag>}</span></div> }, { title: '告警类型', dataIndex: 'type' }, { title: '监测范围', dataIndex: 'target' }, { title: '触发条件', dataIndex: 'threshold' }, { title: '持续时长', dataIndex: 'duration' }, { title: '状态', dataIndex: 'enabled', render: (enabled: boolean, record: Rule) => <Space><Switch size="small" checked={enabled} disabled={record.type === '异常行为'} onChange={(checked) => { setRules((current) => current.map((item) => item.id === record.id ? { ...item, enabled: checked } : item)); messageApi.success(checked ? '规则已启用' : '规则已停用') }} /><span>{enabled ? '启用' : '停用'}</span></Space> }, { title: '更新时间', dataIndex: 'updated' }, { title: '操作', render: (_: unknown, record: Rule) => <Space><Button type="link" size="small" icon={<EditOutlined />} disabled={record.type === '异常行为'}>编辑</Button><Button type="link" size="small" danger icon={<DeleteOutlined />} disabled={record.type === '异常行为'} onClick={() => Modal.confirm({ title: '确认删除规则？', icon: <QuestionCircleOutlined />, content: `删除后「${record.name}」将永久移除，是否继续？`, okText: '删除', cancelText: '取消', okButtonProps: { danger: true }, onOk: () => { setRules((current) => current.filter((item) => item.id !== record.id)); messageApi.success('规则已删除') } })}>删除</Button></Space> }]} /></Card><div className="rule-footnote"><span><i className="inline-dot green" />规则命中后将触发事件去重与风暴防护</span><span>当前生效规则 3 条</span></div><Modal title="新增告警规则" open={modalOpen} onCancel={() => setModalOpen(false)} onOk={() => { setModalOpen(false); messageApi.success('规则新增成功') }} okText="保存" cancelText="取消"><Form layout="vertical"><Form.Item label="规则名称" required><Input placeholder="例如：西门入口超员" /></Form.Item><Form.Item label="告警类型" required><Select defaultValue="超员告警" options={['超员告警', '聚集告警'].map((value) => ({ value, label: value }))} /></Form.Item><Form.Item label="监测范围" required><Select placeholder="选择统计区域" options={['研发楼 A 座 · 一层大厅', '食堂一层 · 入口大厅', '园区南门 · 人行通道'].map((value) => ({ value, label: value }))} /></Form.Item></Form></Modal></div>
}
