import { Button, Card, Col, Drawer, Form, Input, List, Modal, Row, Select, Space, Table, Tabs, Tag, Tooltip, Typography, message } from 'antd'
import { EditOutlined, PlusOutlined, SaveOutlined, SettingOutlined, VideoCameraOutlined } from '@ant-design/icons'
import { useMemo, useState } from 'react'
import { cameras, groups } from '../mocks/data'
import { StatusTag } from '../components/Charts'

const { Title, Text } = Typography

export default function ConfigPage() {
  const [selectedGroup, setSelectedGroup] = useState('all')
  const [drawerCamera, setDrawerCamera] = useState<(typeof cameras)[number] | null>(null)
  const [addGroupOpen, setAddGroupOpen] = useState(false)
  const [messageApi, contextHolder] = message.useMessage()
  const groupCameras = useMemo(() => selectedGroup === 'all' ? cameras : cameras.filter((item) => item.group === groups.find((group) => group.id === selectedGroup)?.name), [selectedGroup])
  return <div className="page-stack">{contextHolder}<div className="page-heading"><div><Title level={3}>分析配置</Title><Text type="secondary">完成分组、设备关联、算法绑定、计数区域与相机标定配置</Text></div><Tag color="blue">管理员视角</Tag></div><Card className="panel-card config-tabs"><Tabs items={[{ key: 'devices', label: '统计设备管理', children: <DeviceConfig groups={groups} selectedGroup={selectedGroup} setSelectedGroup={setSelectedGroup} cameras={groupCameras} onAddGroup={() => setAddGroupOpen(true)} onOpenCamera={setDrawerCamera} /> }, { key: 'calibration', label: '平面图相机标定', children: <Calibration cameras={cameras} messageApi={messageApi} /> }]} /></Card><Modal title="新增统计分组" open={addGroupOpen} onCancel={() => setAddGroupOpen(false)} onOk={() => { setAddGroupOpen(false); messageApi.success('新增成功') }} okText="确定" cancelText="取消"><Form layout="vertical"><Form.Item label="分组名称" name="name" rules={[{ required: true, message: '请输入分组名称' }, { max: 20, message: '分组名称不能超过 20 个字符' }]}><Input placeholder="请输入 1-20 个字符" maxLength={20} /></Form.Item></Form></Modal><Drawer title={drawerCamera ? `设备配置 · ${drawerCamera.name}` : ''} width="72%" open={Boolean(drawerCamera)} onClose={() => setDrawerCamera(null)} destroyOnClose>{drawerCamera && <CameraDrawer camera={drawerCamera} messageApi={messageApi} />}</Drawer></div>
}

function DeviceConfig({ groups: groupList, selectedGroup, setSelectedGroup, cameras: list, onAddGroup, onOpenCamera }: { groups: typeof groups; selectedGroup: string; setSelectedGroup: (id: string) => void; cameras: typeof cameras; onAddGroup: () => void; onOpenCamera: (camera: (typeof cameras)[number]) => void }) {
  return <div className="config-layout"><aside className="group-panel"><div className="group-heading"><strong>统计分析分组</strong><Button type="link" icon={<PlusOutlined />} onClick={onAddGroup}>新增分组</Button></div><List dataSource={groupList} renderItem={(group) => <List.Item className={`group-item ${selectedGroup === group.id ? 'group-selected' : ''}`} onClick={() => setSelectedGroup(group.id)}><div><strong>{group.name}</strong><Text type="secondary">{group.count} 台设备</Text></div><Space><span className="group-active-dot" />{group.id !== 'all' && <Tooltip title="编辑分组"><Button type="text" size="small" icon={<EditOutlined />} /></Tooltip>}</Space></List.Item>} /></aside><section className="device-panel"><div className="subpage-heading"><div><strong>{groupList.find((item) => item.id === selectedGroup)?.name}</strong><Text type="secondary">已关联设备 {list.length} 台</Text></div><Space><Button icon={<PlusOutlined />}>关联新设备</Button><Button icon={<SettingOutlined />}>配置规则</Button></Space></div><Table rowKey="id" scroll={{ x: 860 }} dataSource={list} pagination={false} columns={[{ title: '设备名称', dataIndex: 'name', render: (name: string, record: (typeof cameras)[number]) => <div className="device-name"><VideoCameraOutlined /><span><strong>{name}</strong><Text type="secondary">{record.area}</Text></span></div> }, { title: '所属分组', dataIndex: 'group' }, { title: '在线状态', dataIndex: 'online', render: (online: boolean) => <Tag color={online ? 'green' : 'default'}>{online ? '在线' : '离线'}</Tag> }, { title: '配置状态', dataIndex: 'status', render: (status: string) => <StatusTag status={status} /> }, { title: '最后更新', render: () => <Text type="secondary">10:42:18</Text> }, { title: '操作', fixed: 'right' as const, render: (_: unknown, record: (typeof cameras)[number]) => <Space><Button type="link" size="small" icon={<SettingOutlined />} onClick={() => onOpenCamera(record)}>配置</Button><Button type="link" size="small" danger>取消关联</Button></Space> }]} /></section></div>
}

function CameraDrawer({ camera, messageApi }: { camera: (typeof cameras)[number]; messageApi: ReturnType<typeof message.useMessage>[0] }) {
  return <div className="drawer-content"><div className="drawer-device-meta"><div className="device-avatar"><VideoCameraOutlined /></div><div><strong>{camera.name}</strong><Text type="secondary">{camera.id} · {camera.group}</Text></div><StatusTag status={camera.status} /></div><Tabs items={[{ key: 'algorithm', label: '算法绑定', children: <Form layout="vertical" className="drawer-form"><Form.Item label="绑定算法" required><Select defaultValue="person-track" options={[{ value: 'person-track', label: '行人检测 / 追踪 / 计数 v2.6' }, { value: 'person-detect', label: '行人检测 v3.1' }]} /></Form.Item><Row gutter={16}><Col span={12}><Form.Item label="检测阈值"><Input defaultValue="0.72" /></Form.Item></Col><Col span={12}><Form.Item label="追踪丢失容忍（帧）"><Input defaultValue="12" /></Form.Item></Col></Row><div className="form-tip">算法中心已就绪 · 最近结果延迟 0.8s</div><Button type="primary" icon={<SaveOutlined />} onClick={() => messageApi.success('算法绑定保存成功')}>保存绑定</Button></Form> }, { key: 'draw', label: '画线 / 画区域', children: <div className="draw-tab"><div className="drawing-surface"><div className="drawing-grid" /><div className="draw-zone"><span>已配置区域 · 入口大厅</span></div><div className="draw-line"><span>A → B · 入口计数线</span></div></div><div className="draw-tools"><Button type="primary">画计数线</Button><Button>画统计区域</Button><div className="draw-list"><div><span className="line-mark" />入口计数线 <Tag color="green">启用</Tag><Button type="link" size="small">编辑</Button></div><div><span className="zone-mark" />入口大厅 <Tag color="green">启用</Tag><Button type="link" size="small">编辑</Button></div></div><Button icon={<SaveOutlined />} onClick={() => messageApi.success('绘制配置保存成功')}>保存当前配置</Button></div></div> }, { key: 'preview', label: '预览校验', children: <div className="preview-tab"><div className="preview-video"><span className="preview-badge">LIVE PREVIEW</span><div className="preview-person p1" /><div className="preview-person p2" /><div className="preview-person p3" /><div className="preview-box b1">person 0.98</div><div className="preview-box b2">person 0.94</div></div><div className="preview-status"><Tag color="green">配置可用</Tag><span>检测框 3 人</span><span>区域人数 2 / 120</span><span>计数线今日进入 1,248</span></div></div> }]} /></div>
}

function Calibration({ cameras: list, messageApi }: { cameras: typeof cameras; messageApi: ReturnType<typeof message.useMessage>[0] }) {
  const [selected, setSelected] = useState(list[0].id)
  const camera = list.find((item) => item.id === selected) ?? list[0]
  return <div className="calibration-layout"><aside className="calibration-list"><div className="group-heading"><strong>摄像头列表</strong><Text type="secondary">{list.length} 台</Text></div>{list.map((item) => <button type="button" className={`calibration-item ${selected === item.id ? 'selected' : ''}`} key={item.id} onClick={() => setSelected(item.id)}><VideoCameraOutlined /><span><strong>{item.name}</strong><Text type="secondary">{item.group}</Text></span><Tag color={item.status === '已标定' ? 'green' : 'default'}>{item.status === '已标定' ? '已标定' : '未标定'}</Tag></button>)}</aside><section className="calibration-workspace"><div className="subpage-heading"><div><strong>{camera.name} · 相机标定</strong><Text type="secondary">在画面与平面图上各点选 4 个对应点，建立单应性映射</Text></div><Space><Button onClick={() => messageApi.info('已清除标定点')}>清除标定</Button><Button type="primary" icon={<SaveOutlined />} onClick={() => messageApi.success('标定保存成功')}>保存标定</Button></Space></div><Row gutter={16}><Col span={12}><Card size="small" title="① 摄像头画面 · 选择地面共面标志"><div className="calibration-canvas camera-calibration"><span className="cal-point cp1">1</span><span className="cal-point cp2">2</span><span className="cal-point cp3">3</span><span className="cal-point cp4">4</span><div className="cal-grid" /></div><Text type="secondary">已选择 4 / 4 个点 · 检测框脚位置将映射到平面图</Text></Card></Col><Col span={12}><Card size="small" title="② 园区平面图 · 选择对应位置"><div className="calibration-canvas map-calibration"><span className="cal-point cp1">1</span><span className="cal-point cp2">2</span><span className="cal-point cp3">3</span><span className="cal-point cp4">4</span><div className="mini-building mb1" /><div className="mini-building mb2" /><div className="mini-building mb3" /></div><Text type="secondary">标定残差 2.8px · 低于阈值 5px · 映射验证正常</Text></Card></Col></Row><div className="calibration-check"><Tag color="green">通过</Tag><span>摄像头已关联分组</span><span>4 对标定点有效</span><span>无三点共线</span><span>当前计入足迹热力图</span></div></section></div>
}
