import { Button, Card, DatePicker, Drawer, Empty, Select, Space, Table, Tag, Typography, message } from 'antd'
import { DownloadOutlined, EyeOutlined, FileExcelOutlined, FilePdfOutlined, ReloadOutlined } from '@ant-design/icons'
import { useState } from 'react'
import { reportSeed } from '../mocks/data'
import { HeatmapBoard, TrendChart } from '../components/Charts'
import { hourlyTrend } from '../mocks/data'

const { Title, Text } = Typography

export default function ReportsPage() {
  const [selected, setSelected] = useState<(typeof reportSeed)[number] | null>(null)
  const [messageApi, contextHolder] = message.useMessage()
  const columns = [{ title: '报表周期', dataIndex: 'period', render: (value: string) => <strong>{value}</strong> }, { title: '类型', dataIndex: 'type', render: (value: string) => <Tag color={value === '日报' ? 'blue' : value === '周报' ? 'purple' : 'cyan'}>{value}</Tag> }, { title: '进入人次', dataIndex: 'enter', render: (value: number) => value.toLocaleString() }, { title: '离开人次', dataIndex: 'leave', render: (value: number) => value.toLocaleString() }, { title: '峰值同时在场', dataIndex: 'peak' }, { title: '告警数', dataIndex: 'alerts', render: (value: number) => <span className={value > 50 ? 'red-text' : ''}>{value}</span> }, { title: '状态', dataIndex: 'status', render: (value: string) => <Tag color="green">{value}</Tag> }, { title: '操作', fixed: 'right' as const, width: 150, render: (_: unknown, record: (typeof reportSeed)[number]) => <Space><Button type="link" size="small" icon={<EyeOutlined />} onClick={() => setSelected(record)}>查看</Button><Button type="link" size="small" icon={<DownloadOutlined />} onClick={() => messageApi.success('导出任务已创建')}>导出</Button></Space> }]
  return <div className="page-stack">{contextHolder}<div className="page-heading"><div><Title level={3}>人流报表</Title><Text type="secondary">日报、周报和月报自动生成，支持查看快照与导出明细</Text></div><Space><Button icon={<ReloadOutlined />} onClick={() => messageApi.success('已检查最新报表')}>刷新</Button><Button type="primary" icon={<DownloadOutlined />} onClick={() => messageApi.success('已创建批量导出任务')}>批量导出</Button></Space></div><Card className="filter-card"><Space wrap><span className="control-label">报表类型</span><Select defaultValue="all" options={[{ value: 'all', label: '全部类型' }, { value: 'day', label: '日报' }, { value: 'week', label: '周报' }, { value: 'month', label: '月报' }]} style={{ width: 130 }} /><span className="control-label">日期范围</span><DatePicker.RangePicker /><Button>查询</Button><Button type="text">重置</Button></Space></Card><Card className="panel-card table-card"><div className="table-card-heading"><div><strong>已生成报表</strong><Text type="secondary">共 4 份 · 保留周期 180 天</Text></div><Tag color="blue">日报每日 08:00 自动生成</Tag></div><Table rowKey="id" scroll={{ x: 900 }} columns={columns} dataSource={reportSeed} pagination={{ pageSize: 8, showTotal: (total) => `共 ${total} 份` }} locale={{ emptyText: <Empty description="暂无报表，等待定时任务生成" /> }} /></Card><Drawer title={selected ? `${selected.type} · ${selected.period}` : ''} width={860} open={Boolean(selected)} onClose={() => setSelected(null)} extra={<Space><Button icon={<FilePdfOutlined />} onClick={() => messageApi.success('PDF 导出任务已创建')}>导出 PDF</Button><Button icon={<FileExcelOutlined />} onClick={() => messageApi.success('Excel 导出任务已创建')}>导出 Excel</Button></Space>}>{selected && <ReportDetail report={selected} />}</Drawer></div>
}

function ReportDetail({ report }: { report: (typeof reportSeed)[number] }) { return <div className="report-detail"><div className="report-cover"><div><Text type="secondary">园区人流分析 · 自动生成报表</Text><Title level={2}>{report.type}</Title><Text>{report.period}</Text></div><Tag color="green">数据完整</Tag></div><div className="report-metrics"><div><Text type="secondary">总进入</Text><strong>{report.enter.toLocaleString()}</strong></div><div><Text type="secondary">总离开</Text><strong>{report.leave.toLocaleString()}</strong></div><div><Text type="secondary">峰值同时在场</Text><strong>{report.peak}</strong></div><div><Text type="secondary">告警次数</Text><strong className="red-text">{report.alerts}</strong></div></div><Card title="分时流量趋势"><TrendChart data={hourlyTrend} height={190} /></Card><Card title="建筑流量排行"><div className="report-ranking">{['研发楼 A 座', '食堂一层', '园区南门', '运动中心'].map((name, index) => <div key={name}><span>{index + 1}</span><strong>{name}</strong><i /><b>{[1248, 986, 832, 458][index].toLocaleString()} 人次</b></div>)}</div></Card><Card title="园区热力图快照"><HeatmapBoard compact /></Card></div> }
