import { Button, Card, Col, DatePicker, Empty, Row, Select, Space, Statistic, Table, Tabs, Tag, Typography, message } from 'antd'
import { BarChartOutlined, DownloadOutlined, LineChartOutlined, RiseOutlined, TeamOutlined } from '@ant-design/icons'
import { useMemo, useState } from 'react'
import { buildingStats, hourlyTrend } from '../mocks/data'
import { MiniBars, TrendChart } from '../components/Charts'

const { Title, Text } = Typography

export default function StatsPage() {
  const [activeTab, setActiveTab] = useState('trend')
  const [messageApi, contextHolder] = message.useMessage()
  const [building, setBuilding] = useState('all')
  const filtered = useMemo(() => building === 'all' ? buildingStats : buildingStats.filter((item) => item.name === building), [building])
  return <div className="page-stack">{contextHolder}<div className="page-heading"><div><Title level={3}>流量统计分析</Title><Text type="secondary">从趋势、排行、停留时长和对比维度深入分析园区客流</Text></div><Space><DatePicker.RangePicker /><Button icon={<DownloadOutlined />} onClick={() => messageApi.success('导出任务已创建，请在右上角查看进度')}>导出数据</Button></Space></div><Card className="filter-card"><Space wrap><span className="control-label">统计范围</span><Select defaultValue="today" options={[{ value: 'today', label: '今日（7月18日）' }, { value: 'yesterday', label: '昨日（7月17日）' }, { value: 'week', label: '近 7 天' }]} style={{ width: 150 }} /><span className="control-label">建筑</span><Select value={building} onChange={setBuilding} style={{ width: 150 }} options={[{ value: 'all', label: '全部建筑' }, ...buildingStats.map((item) => ({ value: item.name, label: item.name }))]} /></Space></Card><Row gutter={16} className="stats-kpi-row"><Col xs={12} xl={6}><Card><Statistic title="总进入人次" value="8,542" prefix={<RiseOutlined />} suffix="人次" valueStyle={{ color: '#1677ff' }} /></Card></Col><Col xs={12} xl={6}><Card><Statistic title="同时在场峰值" value="512" prefix={<TeamOutlined />} suffix="人" valueStyle={{ color: '#16a34a' }} /></Card></Col><Col xs={12} xl={6}><Card><Statistic title="平均停留时长" value="42" prefix={<LineChartOutlined />} suffix="分钟" valueStyle={{ color: '#d97706' }} /></Card></Col><Col xs={12} xl={6}><Card><Statistic title="较昨日" value="8.6" prefix="+" suffix="%" valueStyle={{ color: '#dc2626' }} /></Card></Col></Row><Card className="panel-card stats-tabs"><Tabs activeKey={activeTab} onChange={setActiveTab} items={[{ key: 'trend', label: <span><LineChartOutlined /> 分时趋势</span>, children: <TrendPanel /> }, { key: 'rank', label: <span><BarChartOutlined /> 建筑排行</span>, children: <RankPanel data={filtered} /> }, { key: 'stay', label: <span><TeamOutlined /> 停留时长</span>, children: <StayPanel /> }, { key: 'compare', label: <span>多维度对比</span>, children: <ComparePanel /> }]} /></Card><div className="insight-strip"><div><RiseOutlined /><span><strong>14:00 - 15:00</strong> 为今日流量峰值，较工作日均值高 18.6%</span></div><Button type="link" icon={<DownloadOutlined />} onClick={() => messageApi.info('正在生成分析明细')}>下载分析明细</Button></div></div>
}

function TrendPanel() { return <Row gutter={24}><Col xs={24} xl={16}><div className="chart-header"><span>今日分时进入 / 离开趋势</span><Space><Tag color="blue">进入</Tag><Tag color="green">离开</Tag></Space></div><TrendChart data={hourlyTrend} height={280} /></Col><Col xs={24} xl={8}><div className="mini-insight"><Text type="secondary">峰值时段</Text><strong>14:00 - 15:00</strong><span>同时在场 512 人</span></div><div className="mini-insight"><Text type="secondary">环比变化</Text><strong className="change-up">+8.6%</strong><span>高于昨日同期</span></div><div className="mini-insight"><Text type="secondary">数据完整度</Text><strong>99.2%</strong><span className="success-text">全部 8 台设备在线</span></div></Col></Row> }
function RankPanel({ data }: { data: typeof buildingStats }) { return <Table rowKey="name" dataSource={data} pagination={false} columns={[{ title: '排名', dataIndex: 'rank', width: 70, render: (rank: number) => <span className={`rank-index rank-${rank}`}>{rank}</span> }, { title: '建筑 / 区域', dataIndex: 'name' }, { title: '当前人数', dataIndex: 'current', sorter: (a, b) => a.current - b.current, render: (value: number) => <strong>{value} 人</strong> }, { title: '同时在场峰值', dataIndex: 'peak' }, { title: '今日进入', dataIndex: 'enter', render: (value: number) => value.toLocaleString() }, { title: '环比', dataIndex: 'change', render: (value: number) => <span className={value > 0 ? 'change-up' : 'change-down'}>{value > 0 ? '+' : ''}{value}%</span> }, { title: '操作', render: () => <Button type="link" size="small">查看详情</Button> }]} /> }
function StayPanel() { return <div className="stay-grid"><div className="stay-hero"><Text type="secondary">园区平均停留时长</Text><strong>42 <small>分钟</small></strong><span className="change-up">较昨日 +4.8%</span></div>{['研发楼 A 座', '食堂一层', '园区南门', '运动中心'].map((name, index) => <div className="stay-item" key={name}><div><strong>{name}</strong><span>{[58, 36, 18, 64][index]} 分钟</span></div><MiniBars values={index === 0 ? [4, 6, 8, 7, 9, 11, 10] : [2, 4, 3, 5, 4, 6, 5]} color={['#1677ff', '#16a34a', '#d97706', '#7c3aed'][index]} /></div>)}</div> }
function ComparePanel() { return <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="选择两个以上建筑后查看多维度对比" /> }
